#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AgenciaInmoviliaria")]
	public partial class BDINMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCiudad(Ciudad instance);
    partial void UpdateCiudad(Ciudad instance);
    partial void DeleteCiudad(Ciudad instance);
    partial void InsertVisitas(Visitas instance);
    partial void UpdateVisitas(Visitas instance);
    partial void DeleteVisitas(Visitas instance);
    partial void InsertInmobilaria(Inmobilaria instance);
    partial void UpdateInmobilaria(Inmobilaria instance);
    partial void DeleteInmobilaria(Inmobilaria instance);
    partial void InsertPropietario(Propietario instance);
    partial void UpdatePropietario(Propietario instance);
    partial void DeletePropietario(Propietario instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public BDINMDataContext() : 
				base(global::CDatos.Properties.Settings.Default.AgenciaInmoviliariaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDINMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDINMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDINMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDINMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ciudad> Ciudad
		{
			get
			{
				return this.GetTable<Ciudad>();
			}
		}
		
		public System.Data.Linq.Table<Visitas> Visitas
		{
			get
			{
				return this.GetTable<Visitas>();
			}
		}
		
		public System.Data.Linq.Table<Inmobilaria> Inmobilaria
		{
			get
			{
				return this.GetTable<Inmobilaria>();
			}
		}
		
		public System.Data.Linq.Table<Propietario> Propietario
		{
			get
			{
				return this.GetTable<Propietario>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarInmobilaria")]
		public int CP_InsertarInmobilaria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idInmobilaria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOficinas", DbType="Int")] System.Nullable<int> nOficinas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NReferencia", DbType="Int")] System.Nullable<int> nReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(50)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCiudad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPropietario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVisitas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInmobilaria, nOficinas, nReferencia, tipo, descripcion, idCiudad, precio, idPropietario, idVisitas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarUsuarios")]
		public int CP_InsertarUsuarios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaN", DbType="Date")] System.Nullable<System.DateTime> fechaN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ocupacion", DbType="VarChar(50)")] string ocupacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, cedula, nombre, apellido, fechaN, ocupacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ModificarUsuarios")]
		public int CP_ModificarUsuarios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaN", DbType="Date")] System.Nullable<System.DateTime> fechaN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ocupacion", DbType="VarChar(50)")] string ocupacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, cedula, nombre, apellido, fechaN, ocupacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ModificarInmobilaria")]
		public int CP_ModificarInmobilaria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idInmobilaria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOficinas", DbType="Int")] System.Nullable<int> nOficinas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NReferencia", DbType="Int")] System.Nullable<int> nReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(50)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCiudad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPropietario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVisitas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInmobilaria, nOficinas, nReferencia, tipo, descripcion, idCiudad, precio, idPropietario, idVisitas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarPropietario")]
		public int CP_InsertarPropietario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPropietario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoVivienda", DbType="VarChar(50)")] string estadoVivienda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPropietario, cedula, nombre, apellido, telefono, email, estadoVivienda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ModificarPropietario")]
		public int CP_ModificarPropietario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPropietario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoVivienda", DbType="VarChar(50)")] string estadoVivienda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPropietario, cedula, nombre, apellido, telefono, email, estadoVivienda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarCiudad")]
		public ISingleResult<CP_ListarCiudadResult> CP_ListarCiudad()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarCiudadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarVisitas")]
		public ISingleResult<CP_ListarVisitasResult> CP_ListarVisitas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarVisitasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInmobilaria")]
		public ISingleResult<CP_ListarInmobilariaResult> CP_ListarInmobilaria()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarInmobilariaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarPropietario")]
		public ISingleResult<CP_ListarPropietarioResult> CP_ListarPropietario()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarPropietarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarUsuarios")]
		public ISingleResult<CP_ListarUsuariosResult> CP_ListarUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarInmobilaria")]
		public int CP_EliminarInmobilaria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idInmobilaria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInmobilaria);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarVisitas")]
		public int CP_EliminarVisitas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVisitas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVisitas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarPropietario")]
		public int CP_EliminarPropietario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPropietario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPropietario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarUsuarios")]
		public int CP_EliminarUsuarios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarVisitas")]
		public int CP_InsertarVisitas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVisitas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaV", DbType="Date")] System.Nullable<System.DateTime> fechaV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraV", DbType="Date")] System.Nullable<System.DateTime> horaV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comentario", DbType="VarChar(50)")] string comentario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVisitas, fechaV, horaV, idUsuario, comentario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ModificarVisitas")]
		public int CP_ModificarVisitas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVisitas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaV", DbType="Date")] System.Nullable<System.DateTime> fechaV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraV", DbType="Date")] System.Nullable<System.DateTime> horaV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comentario", DbType="VarChar(50)")] string comentario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVisitas, fechaV, horaV, idUsuario, comentario);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ciudad")]
	public partial class Ciudad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCiudad;
		
		private int _Codigo;
		
		private string _Nombre;
		
		private EntitySet<Inmobilaria> _Inmobilaria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCiudadChanging(int value);
    partial void OnidCiudadChanged();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Ciudad()
		{
			this._Inmobilaria = new EntitySet<Inmobilaria>(new Action<Inmobilaria>(this.attach_Inmobilaria), new Action<Inmobilaria>(this.detach_Inmobilaria));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCiudad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCiudad
		{
			get
			{
				return this._idCiudad;
			}
			set
			{
				if ((this._idCiudad != value))
				{
					this.OnidCiudadChanging(value);
					this.SendPropertyChanging();
					this._idCiudad = value;
					this.SendPropertyChanged("idCiudad");
					this.OnidCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Inmobilaria", Storage="_Inmobilaria", ThisKey="idCiudad", OtherKey="idCiudad")]
		public EntitySet<Inmobilaria> Inmobilaria
		{
			get
			{
				return this._Inmobilaria;
			}
			set
			{
				this._Inmobilaria.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Inmobilaria(Inmobilaria entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad = this;
		}
		
		private void detach_Inmobilaria(Inmobilaria entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visitas")]
	public partial class Visitas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idVisitas;
		
		private System.DateTime _FechaV;
		
		private System.DateTime _HoraV;
		
		private int _idUsuario;
		
		private string _Comentario;
		
		private EntitySet<Inmobilaria> _Inmobilaria;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVisitasChanging(int value);
    partial void OnidVisitasChanged();
    partial void OnFechaVChanging(System.DateTime value);
    partial void OnFechaVChanged();
    partial void OnHoraVChanging(System.DateTime value);
    partial void OnHoraVChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    #endregion
		
		public Visitas()
		{
			this._Inmobilaria = new EntitySet<Inmobilaria>(new Action<Inmobilaria>(this.attach_Inmobilaria), new Action<Inmobilaria>(this.detach_Inmobilaria));
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVisitas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idVisitas
		{
			get
			{
				return this._idVisitas;
			}
			set
			{
				if ((this._idVisitas != value))
				{
					this.OnidVisitasChanging(value);
					this.SendPropertyChanging();
					this._idVisitas = value;
					this.SendPropertyChanged("idVisitas");
					this.OnidVisitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaV", DbType="Date NOT NULL")]
		public System.DateTime FechaV
		{
			get
			{
				return this._FechaV;
			}
			set
			{
				if ((this._FechaV != value))
				{
					this.OnFechaVChanging(value);
					this.SendPropertyChanging();
					this._FechaV = value;
					this.SendPropertyChanged("FechaV");
					this.OnFechaVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraV", DbType="Date NOT NULL")]
		public System.DateTime HoraV
		{
			get
			{
				return this._HoraV;
			}
			set
			{
				if ((this._HoraV != value))
				{
					this.OnHoraVChanging(value);
					this.SendPropertyChanging();
					this._HoraV = value;
					this.SendPropertyChanged("HoraV");
					this.OnHoraVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visitas_Inmobilaria", Storage="_Inmobilaria", ThisKey="idVisitas", OtherKey="idVisitas")]
		public EntitySet<Inmobilaria> Inmobilaria
		{
			get
			{
				return this._Inmobilaria;
			}
			set
			{
				this._Inmobilaria.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Visitas", Storage="_Usuarios", ThisKey="idUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Visitas.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Visitas.Add(this);
						this._idUsuario = value.idUsuario;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Inmobilaria(Inmobilaria entity)
		{
			this.SendPropertyChanging();
			entity.Visitas = this;
		}
		
		private void detach_Inmobilaria(Inmobilaria entity)
		{
			this.SendPropertyChanging();
			entity.Visitas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inmobilaria")]
	public partial class Inmobilaria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idInmobilaria;
		
		private int _NOficinas;
		
		private int _NReferencia;
		
		private string _Tipo;
		
		private string _Descripcion;
		
		private int _idCiudad;
		
		private decimal _Precio;
		
		private int _idPropietario;
		
		private int _idVisitas;
		
		private EntityRef<Ciudad> _Ciudad;
		
		private EntityRef<Visitas> _Visitas;
		
		private EntityRef<Propietario> _Propietario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidInmobilariaChanging(int value);
    partial void OnidInmobilariaChanged();
    partial void OnNOficinasChanging(int value);
    partial void OnNOficinasChanged();
    partial void OnNReferenciaChanging(int value);
    partial void OnNReferenciaChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnidCiudadChanging(int value);
    partial void OnidCiudadChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    partial void OnidPropietarioChanging(int value);
    partial void OnidPropietarioChanged();
    partial void OnidVisitasChanging(int value);
    partial void OnidVisitasChanged();
    #endregion
		
		public Inmobilaria()
		{
			this._Ciudad = default(EntityRef<Ciudad>);
			this._Visitas = default(EntityRef<Visitas>);
			this._Propietario = default(EntityRef<Propietario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInmobilaria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idInmobilaria
		{
			get
			{
				return this._idInmobilaria;
			}
			set
			{
				if ((this._idInmobilaria != value))
				{
					this.OnidInmobilariaChanging(value);
					this.SendPropertyChanging();
					this._idInmobilaria = value;
					this.SendPropertyChanged("idInmobilaria");
					this.OnidInmobilariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOficinas", DbType="Int NOT NULL")]
		public int NOficinas
		{
			get
			{
				return this._NOficinas;
			}
			set
			{
				if ((this._NOficinas != value))
				{
					this.OnNOficinasChanging(value);
					this.SendPropertyChanging();
					this._NOficinas = value;
					this.SendPropertyChanged("NOficinas");
					this.OnNOficinasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NReferencia", DbType="Int NOT NULL")]
		public int NReferencia
		{
			get
			{
				return this._NReferencia;
			}
			set
			{
				if ((this._NReferencia != value))
				{
					this.OnNReferenciaChanging(value);
					this.SendPropertyChanging();
					this._NReferencia = value;
					this.SendPropertyChanged("NReferencia");
					this.OnNReferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCiudad", DbType="Int NOT NULL")]
		public int idCiudad
		{
			get
			{
				return this._idCiudad;
			}
			set
			{
				if ((this._idCiudad != value))
				{
					if (this._Ciudad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCiudadChanging(value);
					this.SendPropertyChanging();
					this._idCiudad = value;
					this.SendPropertyChanged("idCiudad");
					this.OnidCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,2) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPropietario", DbType="Int NOT NULL")]
		public int idPropietario
		{
			get
			{
				return this._idPropietario;
			}
			set
			{
				if ((this._idPropietario != value))
				{
					if (this._Propietario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPropietarioChanging(value);
					this.SendPropertyChanging();
					this._idPropietario = value;
					this.SendPropertyChanged("idPropietario");
					this.OnidPropietarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVisitas", DbType="Int NOT NULL")]
		public int idVisitas
		{
			get
			{
				return this._idVisitas;
			}
			set
			{
				if ((this._idVisitas != value))
				{
					if (this._Visitas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVisitasChanging(value);
					this.SendPropertyChanging();
					this._idVisitas = value;
					this.SendPropertyChanged("idVisitas");
					this.OnidVisitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Inmobilaria", Storage="_Ciudad", ThisKey="idCiudad", OtherKey="idCiudad", IsForeignKey=true)]
		public Ciudad Ciudad
		{
			get
			{
				return this._Ciudad.Entity;
			}
			set
			{
				Ciudad previousValue = this._Ciudad.Entity;
				if (((previousValue != value) 
							|| (this._Ciudad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciudad.Entity = null;
						previousValue.Inmobilaria.Remove(this);
					}
					this._Ciudad.Entity = value;
					if ((value != null))
					{
						value.Inmobilaria.Add(this);
						this._idCiudad = value.idCiudad;
					}
					else
					{
						this._idCiudad = default(int);
					}
					this.SendPropertyChanged("Ciudad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visitas_Inmobilaria", Storage="_Visitas", ThisKey="idVisitas", OtherKey="idVisitas", IsForeignKey=true)]
		public Visitas Visitas
		{
			get
			{
				return this._Visitas.Entity;
			}
			set
			{
				Visitas previousValue = this._Visitas.Entity;
				if (((previousValue != value) 
							|| (this._Visitas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Visitas.Entity = null;
						previousValue.Inmobilaria.Remove(this);
					}
					this._Visitas.Entity = value;
					if ((value != null))
					{
						value.Inmobilaria.Add(this);
						this._idVisitas = value.idVisitas;
					}
					else
					{
						this._idVisitas = default(int);
					}
					this.SendPropertyChanged("Visitas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Propietario_Inmobilaria", Storage="_Propietario", ThisKey="idPropietario", OtherKey="idPropietario", IsForeignKey=true)]
		public Propietario Propietario
		{
			get
			{
				return this._Propietario.Entity;
			}
			set
			{
				Propietario previousValue = this._Propietario.Entity;
				if (((previousValue != value) 
							|| (this._Propietario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Propietario.Entity = null;
						previousValue.Inmobilaria.Remove(this);
					}
					this._Propietario.Entity = value;
					if ((value != null))
					{
						value.Inmobilaria.Add(this);
						this._idPropietario = value.idPropietario;
					}
					else
					{
						this._idPropietario = default(int);
					}
					this.SendPropertyChanged("Propietario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Propietario")]
	public partial class Propietario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPropietario;
		
		private System.Data.Linq.Binary _Cedula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Telefono;
		
		private string _Email;
		
		private string _EstadoVivienda;
		
		private EntitySet<Inmobilaria> _Inmobilaria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPropietarioChanging(int value);
    partial void OnidPropietarioChanged();
    partial void OnCedulaChanging(System.Data.Linq.Binary value);
    partial void OnCedulaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEstadoViviendaChanging(string value);
    partial void OnEstadoViviendaChanged();
    #endregion
		
		public Propietario()
		{
			this._Inmobilaria = new EntitySet<Inmobilaria>(new Action<Inmobilaria>(this.attach_Inmobilaria), new Action<Inmobilaria>(this.detach_Inmobilaria));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPropietario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idPropietario
		{
			get
			{
				return this._idPropietario;
			}
			set
			{
				if ((this._idPropietario != value))
				{
					this.OnidPropietarioChanging(value);
					this.SendPropertyChanging();
					this._idPropietario = value;
					this.SendPropertyChanged("idPropietario");
					this.OnidPropietarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarBinary(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoVivienda", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EstadoVivienda
		{
			get
			{
				return this._EstadoVivienda;
			}
			set
			{
				if ((this._EstadoVivienda != value))
				{
					this.OnEstadoViviendaChanging(value);
					this.SendPropertyChanging();
					this._EstadoVivienda = value;
					this.SendPropertyChanged("EstadoVivienda");
					this.OnEstadoViviendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Propietario_Inmobilaria", Storage="_Inmobilaria", ThisKey="idPropietario", OtherKey="idPropietario")]
		public EntitySet<Inmobilaria> Inmobilaria
		{
			get
			{
				return this._Inmobilaria;
			}
			set
			{
				this._Inmobilaria.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Inmobilaria(Inmobilaria entity)
		{
			this.SendPropertyChanging();
			entity.Propietario = this;
		}
		
		private void detach_Inmobilaria(Inmobilaria entity)
		{
			this.SendPropertyChanging();
			entity.Propietario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.DateTime _FechaN;
		
		private string _Ocupacion;
		
		private EntitySet<Visitas> _Visitas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnFechaNChanging(System.DateTime value);
    partial void OnFechaNChanged();
    partial void OnOcupacionChanging(string value);
    partial void OnOcupacionChanged();
    #endregion
		
		public Usuarios()
		{
			this._Visitas = new EntitySet<Visitas>(new Action<Visitas>(this.attach_Visitas), new Action<Visitas>(this.detach_Visitas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaN", DbType="Date NOT NULL")]
		public System.DateTime FechaN
		{
			get
			{
				return this._FechaN;
			}
			set
			{
				if ((this._FechaN != value))
				{
					this.OnFechaNChanging(value);
					this.SendPropertyChanging();
					this._FechaN = value;
					this.SendPropertyChanged("FechaN");
					this.OnFechaNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ocupacion
		{
			get
			{
				return this._Ocupacion;
			}
			set
			{
				if ((this._Ocupacion != value))
				{
					this.OnOcupacionChanging(value);
					this.SendPropertyChanging();
					this._Ocupacion = value;
					this.SendPropertyChanged("Ocupacion");
					this.OnOcupacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Visitas", Storage="_Visitas", ThisKey="idUsuario", OtherKey="idUsuario")]
		public EntitySet<Visitas> Visitas
		{
			get
			{
				return this._Visitas;
			}
			set
			{
				this._Visitas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Visitas(Visitas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Visitas(Visitas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	public partial class CP_ListarCiudadResult
	{
		
		private int _idCiudad;
		
		private int _Codigo;
		
		private string _Nombre;
		
		public CP_ListarCiudadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCiudad", DbType="Int NOT NULL")]
		public int idCiudad
		{
			get
			{
				return this._idCiudad;
			}
			set
			{
				if ((this._idCiudad != value))
				{
					this._idCiudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class CP_ListarVisitasResult
	{
		
		private int _idVisitas;
		
		private System.DateTime _FechaV;
		
		private System.DateTime _HoraV;
		
		private int _idUsuario;
		
		private string _Comentario;
		
		public CP_ListarVisitasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVisitas", DbType="Int NOT NULL")]
		public int idVisitas
		{
			get
			{
				return this._idVisitas;
			}
			set
			{
				if ((this._idVisitas != value))
				{
					this._idVisitas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaV", DbType="Date NOT NULL")]
		public System.DateTime FechaV
		{
			get
			{
				return this._FechaV;
			}
			set
			{
				if ((this._FechaV != value))
				{
					this._FechaV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraV", DbType="Date NOT NULL")]
		public System.DateTime HoraV
		{
			get
			{
				return this._HoraV;
			}
			set
			{
				if ((this._HoraV != value))
				{
					this._HoraV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInmobilariaResult
	{
		
		private int _idInmobilaria;
		
		private int _NOficinas;
		
		private int _NReferencia;
		
		private string _Tipo;
		
		private string _Descripcion;
		
		private int _idCiudad;
		
		private decimal _Precio;
		
		private int _idPropietario;
		
		private int _idVisitas;
		
		public CP_ListarInmobilariaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInmobilaria", DbType="Int NOT NULL")]
		public int idInmobilaria
		{
			get
			{
				return this._idInmobilaria;
			}
			set
			{
				if ((this._idInmobilaria != value))
				{
					this._idInmobilaria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOficinas", DbType="Int NOT NULL")]
		public int NOficinas
		{
			get
			{
				return this._NOficinas;
			}
			set
			{
				if ((this._NOficinas != value))
				{
					this._NOficinas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NReferencia", DbType="Int NOT NULL")]
		public int NReferencia
		{
			get
			{
				return this._NReferencia;
			}
			set
			{
				if ((this._NReferencia != value))
				{
					this._NReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCiudad", DbType="Int NOT NULL")]
		public int idCiudad
		{
			get
			{
				return this._idCiudad;
			}
			set
			{
				if ((this._idCiudad != value))
				{
					this._idCiudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,2) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPropietario", DbType="Int NOT NULL")]
		public int idPropietario
		{
			get
			{
				return this._idPropietario;
			}
			set
			{
				if ((this._idPropietario != value))
				{
					this._idPropietario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVisitas", DbType="Int NOT NULL")]
		public int idVisitas
		{
			get
			{
				return this._idVisitas;
			}
			set
			{
				if ((this._idVisitas != value))
				{
					this._idVisitas = value;
				}
			}
		}
	}
	
	public partial class CP_ListarPropietarioResult
	{
		
		private int _idPropietario;
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Telefono;
		
		private string _Email;
		
		private string _EstadoVivienda;
		
		public CP_ListarPropietarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPropietario", DbType="Int NOT NULL")]
		public int idPropietario
		{
			get
			{
				return this._idPropietario;
			}
			set
			{
				if ((this._idPropietario != value))
				{
					this._idPropietario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoVivienda", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EstadoVivienda
		{
			get
			{
				return this._EstadoVivienda;
			}
			set
			{
				if ((this._EstadoVivienda != value))
				{
					this._EstadoVivienda = value;
				}
			}
		}
	}
	
	public partial class CP_ListarUsuariosResult
	{
		
		private int _idUsuario;
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.DateTime _FechaN;
		
		private string _Ocupacion;
		
		public CP_ListarUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaN", DbType="Date NOT NULL")]
		public System.DateTime FechaN
		{
			get
			{
				return this._FechaN;
			}
			set
			{
				if ((this._FechaN != value))
				{
					this._FechaN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ocupacion
		{
			get
			{
				return this._Ocupacion;
			}
			set
			{
				if ((this._Ocupacion != value))
				{
					this._Ocupacion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
